# -*- coding: utf-8 -*-
"""Телеграмм-бот "Онлайн-Поликлиника"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TFvTZHtisPGNZARKMJngxCZ7u4rw7Cd1
"""

# -*- coding: utf-8 -*-

"""
Основной файл телеграмм-бота "Онлайн-Поликлиника"
для пациентов с постинсультным таламическим синдромом.

Этот бот использует python-telegram-bot и Firebase Firestore.
"""

import logging
import os
import json
import datetime
import asyncio
from telegram import Update, ReplyKeyboardMarkup, ReplyKeyboardRemove, KeyboardButton
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    ConversationHandler,
    ContextTypes,
    filters,
)
import firebase_admin
from firebase_admin import credentials, firestore, auth

# --- КОНФИГУРАЦИЯ ---

# Переменные среды для Render
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME")
# FIREBASE_CONFIG_JSON - содержит JSON ключа сервисного аккаунта в виде строки
FIREBASE_CONFIG_JSON = os.getenv("FIREBASE_CONFIG_JSON")

# Константы для Webhook
PORT = int(os.environ.get("PORT", "10000"))
WEBHOOK_PATH = TELEGRAM_TOKEN or "secret-path"
WEBHOOK_URL = f"{RENDER_EXTERNAL_HOSTNAME}/{WEBHOOK_PATH}" if RENDER_EXTERNAL_HOSTNAME else None

# Константы для бота
(
    Q1_PAIN,
    Q2_SLEEP,
    Q3_MEDICATION,
    Q4_SIDE_EFFECTS,
    Q5_COMMENTS,
    FEEDBACK
) = range(6)

# Текстовые константы
SURVEY_BTN = "📊 Начать опрос"
FEEDBACK_BTN = "✉️ Обратная связь"
ILLNESS_BTN = "🧠 О синдроме"
INFO_BTN = "❓ Помощь"
EMERGENCY_BTN = "🚨 Экстренный вызов"
CANCEL_BTN = "❌ Отмена"

# Настройка логирования
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)
logger = logging.getLogger(__name__)

# --- Инициализация Firebase ---

db = None
firebase_app_id = "default-app-id" # Запасное значение, если не получено

def init_firebase():
    """Инициализирует Firebase Admin SDK."""
    global db
    global firebase_app_id

    if FIREBASE_CONFIG_JSON:
        try:
            # Парсинг JSON-строки из переменной среды
            cred_json = json.loads(FIREBASE_CONFIG_JSON)
            
            # Извлечение project_id из ключа для использования в качестве appId
            firebase_app_id = cred_json.get("project_id", "default-app-id")

            # Инициализация с помощью учетных данных сервисного аккаунта
            cred = credentials.Certificate(cred_json)
            firebase_admin.initialize_app(cred)
            db = firestore.client()
            logger.info(f"✅ Firebase Admin SDK успешно инициализирован (Project: {firebase_app_id}).")
            
        except json.JSONDecodeError:
            logger.error(f"❌ Ошибка инициализации Firebase/Firestore: Неверный формат JSON в FIREBASE_CONFIG_JSON.")
        except Exception as e:
            logger.error(f"❌ Критическая ошибка при инициализации Firebase: {e}")
    else:
        logger.warning("⚠️ Переменная FIREBASE_CONFIG_JSON не найдена. Firebase не инициализирован. Данные будут храниться только локально (если бы это не был реальный бот).")

# --- Утилиты Firebase (сохранение) ---

def get_user_doc_ref(user_id: str):
    """Возвращает ссылку на документ профиля пользователя."""
    # Используем project_id как appId
    return db.collection(f"artifacts/{firebase_app_id}/users/{user_id}/profile").document("info")

def get_survey_collection_ref(user_id: str):
    """Возвращает ссылку на коллекцию опросов пользователя."""
    return db.collection(f"artifacts/{firebase_app_id}/users/{user_id}/surveys")

def get_feedback_collection_ref(user_id: str):
    """Возвращает ссылку на коллекцию обратной связи пользователя."""
    return db.collection(f"artifacts/{firebase_app_id}/users/{user_id}/feedback")

async def save_user_profile(user_data: dict, user_id: int):
    """Сохраняет или обновляет профиль пользователя в Firestore."""
    if db is None:
        logger.warning("Не удалось сохранить профиль: DB не инициализирована.")
        return

    try:
        doc_ref = get_user_doc_ref(str(user_id))
        await asyncio.to_thread(doc_ref.set, user_data, merge=True)
        logger.info(f"Профиль пользователя {user_id} сохранен/обновлен.")
    except Exception as e:
        logger.error(f"Ошибка сохранения профиля пользователя {user_id}: {e}")

async def save_survey_results(user_id: int, results: dict):
    """Сохраняет результаты опроса в Firestore."""
    if db is None:
        logger.warning("Не удалось сохранить опрос: DB не инициализирована.")
        return

    try:
        # Добавляем метку времени
        results["timestamp"] = datetime.datetime.now(datetime.timezone.utc)
        results["user_id"] = str(user_id)
        
        collection_ref = get_survey_collection_ref(str(user_id))
        await asyncio.to_thread(collection_ref.add, results)
        logger.info(f"Результаты опроса для пользователя {user_id} сохранены.")
    except Exception as e:
        logger.error(f"Ошибка сохранения результатов опроса для пользователя {user_id}: {e}")

async def save_feedback(user_id: int, text: str):
    """Сохраняет сообщение обратной связи в Firestore."""
    if db is None:
        logger.warning("Не удалось сохранить обратную связь: DB не инициализирована.")
        return

    try:
        data = {
            "text": text,
            "timestamp": datetime.datetime.now(datetime.timezone.utc),
            "user_id": str(user_id)
        }
        collection_ref = get_feedback_collection_ref(str(user_id))
        await asyncio.to_thread(collection_ref.add, data)
        logger.info(f"Обратная связь от пользователя {user_id} сохранена.")
    except Exception as e:
        logger.error(f"Ошибка сохранения обратной связи для пользователя {user_id}: {e}")

# --- Функции клавиатуры и меню ---

def get_main_menu_keyboard():
    """Возвращает разметку для главного меню."""
    # Используем кнопки в ряд
    keyboard = [
        [SURVEY_BTN, FEEDBACK_BTN],
        [ILLNESS_BTN, INFO_BTN],
        [KeyboardButton(EMERGENCY_BTN)],
    ]
    return ReplyKeyboardMarkup(keyboard, resize_keyboard=True, one_time_keyboard=False)

def get_cancel_keyboard():
    """Возвращает клавиатуру только с кнопкой отмены."""
    return ReplyKeyboardMarkup([[CANCEL_BTN]], resize_keyboard=True, one_time_keyboard=True)

# --- Функции обработчиков (Handlers) ---

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Обрабатывает команду /start и приветствует пользователя."""
    user = update.effective_user
    
    # Сохраняем информацию о пользователе
    user_data = {
        "first_name": user.first_name,
        "last_name": user.last_name,
        "username": user.username,
        "language_code": user.language_code,
        "chat_id": update.effective_chat.id,
        "last_login": datetime.datetime.now(datetime.timezone.utc)
    }
    # Запускаем асинхронную задачу сохранения, не блокируя основной поток
    asyncio.create_task(save_user_profile(user_data, user.id))

    await update.message.reply_html(
        f"Здравствуйте, {user.mention_html()}! Я бот-помощник \"Онлайн-Поликлиники\", созданный для поддержки пациентов с постинсультным таламическим синдромом. "
        "Я могу помочь вам ежедневно отслеживать ваше состояние, сохранять важные данные для вашего врача и предоставить справочную информацию.\n\n"
        "Выберите действие в меню ниже.",
        reply_markup=get_main_menu_keyboard(),
    )

async def show_illness_info(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Показывает справочную информацию о синдроме."""
    info_text = (
        "🧠 **Постинсультный таламический синдром (синдром Дежерин-Русси)**\n\n"
        "Это комплекс неврологических нарушений, возникающих после повреждения таламуса в результате инсульта. "
        "Его главной характеристикой является **таламическая боль** — сильная, часто жгучая, трудно поддающаяся лечению боль. "
        "Симптомы могут также включать онемение, повышенную чувствительность к раздражителям (аллодиния), "
        "нарушения сна, эмоциональные расстройства и двигательные нарушения.\n\n"
        "**Цель нашего бота** — помочь вам ежедневно отслеживать интенсивность этих симптомов, чтобы ваш врач мог максимально точно скорректировать терапию."
    )
    await update.message.reply_text(info_text, reply_markup=get_main_menu_keyboard(), parse_mode="Markdown")

async def show_info(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Показывает информацию об использовании бота."""
    info_text = (
        "❓ **Как пользоваться ботом**\n\n"
        "1. **📊 Начать опрос:** Ежедневно отвечайте на 5 простых вопросов о боли, сне и приеме лекарств. "
        "Это позволяет вести точный дневник вашего состояния. Все данные сохраняются в базу Firestore.\n"
        "2. **✉️ Обратная связь:** Отправьте сообщение для вашего врача или команды поддержки.\n"
        "3. **🧠 О синдроме:** Узнайте больше о вашем заболевании.\n"
        "4. **🚨 Экстренный вызов:** Получите контактные данные для неотложной помощи.\n\n"
        "**Внимание:** Этот бот не является заменой медицинскому специалисту или экстренной службе. Всегда консультируйтесь с врачом!"
    )
    await update.message.reply_text(info_text, reply_markup=get_main_menu_keyboard(), parse_mode="Markdown")

async def show_emergency(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Показывает информацию для экстренных случаев."""
    emergency_text = (
        "🚨 **ЭКСТРЕННАЯ ПОМОЩЬ**\n\n"
        "Если вы чувствуете резкое ухудшение состояния, пожалуйста, немедленно обратитесь к врачу или вызовите скорую помощь!\n\n"
        "📞 **Единый номер экстренных служб (Россия):** `112`\n"
        "📞 **Ваш лечащий врач/клиника:** [Место для контактов вашего врача или клиники]\n\n"
        "**НЕ ИСПОЛЬЗУЙТЕ ЭТОТ БОТ ДЛЯ ЭКСТРЕННЫХ СЛУЧАЕВ.**"
    )
    await update.message.reply_text(emergency_text, reply_markup=get_main_menu_keyboard(), parse_mode="Markdown")

# --- Диалог Обратной связи ---

async def feedback_start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Начинает диалог обратной связи."""
    await update.message.reply_text(
        "Напишите ваше сообщение, вопрос или комментарий. Мы передадим его врачу или команде поддержки.\n"
        "Для отмены нажмите \"❌ Отмена\".",
        reply_markup=get_cancel_keyboard()
    )
    return FEEDBACK

async def feedback_process(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Обрабатывает и сохраняет сообщение обратной связи."""
    text = update.message.text
    user_id = update.effective_user.id
    
    # Сохраняем обратную связь
    asyncio.create_task(save_feedback(user_id, text))
    
    await update.message.reply_text(
        "Спасибо! Ваше сообщение принято и будет рассмотрено. Если потребуется ответ, мы свяжемся с вами.",
        reply_markup=get_main_menu_keyboard()
    )
    return ConversationHandler.END

# --- Диалог Опроса (Survey) ---

async def survey_start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Начинает диалог опроса. Вопрос 1: Интенсивность боли."""
    context.user_data["survey_data"] = {}
    
    keyboard = [[KeyboardButton(str(i)) for i in range(0, 6)],
                [KeyboardButton(str(i)) for i in range(6, 11)]]
    
    await update.message.reply_text(
        "**📊 Ежедневный опрос**\n\n"
        "**Вопрос 1/5:** Оцените интенсивность вашей таламической боли по шкале от 0 (нет боли) до 10 (самая сильная боль, которую вы можете себе представить).",
        reply_markup=ReplyKeyboardMarkup(keyboard, resize_keyboard=True, one_time_keyboard=True),
        parse_mode="Markdown"
    )
    return Q1_PAIN

async def q1_pain(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Вопрос 2: Качество сна."""
    try:
        pain_score = int(update.message.text)
        if not 0 <= pain_score <= 10:
            raise ValueError
        context.user_data["survey_data"]["pain_score"] = pain_score
    except ValueError:
        await update.message.reply_text("Пожалуйста, введите число от 0 до 10.")
        return Q1_PAIN

    keyboard = [["Отлично", "Хорошо", "Удовлетворительно"], ["Плохо", "Очень плохо"]]
    
    await update.message.reply_text(
        "**Вопрос 2/5:** Как вы оцените качество вашего сна прошлой ночью?",
        reply_markup=ReplyKeyboardMarkup(keyboard, resize_keyboard=True, one_time_keyboard=True)
    )
    return Q2_SLEEP

async def q2_sleep(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Вопрос 3: Прием лекарств."""
    sleep_quality = update.message.text
    if sleep_quality not in ["Отлично", "Хорошо", "Удовлетворительно", "Плохо", "Очень плохо"]:
         await update.message.reply_text("Пожалуйста, выберите один из предложенных вариантов качества сна.")
         return Q2_SLEEP

    context.user_data["survey_data"]["sleep_quality"] = sleep_quality
    
    keyboard = [["Да", "Нет"]]
    
    await update.message.reply_text(
        "**Вопрос 3/5:** Принимали ли вы сегодня прописанные обезболивающие препараты (например, антиконвульсанты или антидепрессанты)?",
        reply_markup=ReplyKeyboardMarkup(keyboard, resize_keyboard=True, one_time_keyboard=True)
    )
    return Q3_MEDICATION

async def q3_medication(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Вопрос 4: Побочные эффекты."""
    medication_taken = update.message.text
    if medication_taken not in ["Да", "Нет"]:
        await update.message.reply_text("Пожалуйста, ответьте 'Да' или 'Нет'.")
        return Q3_MEDICATION

    context.user_data["survey_data"]["medication_taken"] = medication_taken
    
    await update.message.reply_text(
        "**Вопрос 4/5:** Опишите, какие побочные эффекты (если таковые имеются) вы заметили сегодня. "
        "Если побочных эффектов нет, напишите 'Нет'.",
        reply_markup=get_cancel_keyboard()
    )
    return Q4_SIDE_EFFECTS

async def q4_side_effects(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Вопрос 5: Дополнительные комментарии."""
    side_effects = update.message.text
    context.user_data["survey_data"]["side_effects"] = side_effects
    
    await update.message.reply_text(
        "**Вопрос 5/5:** Хотите ли вы добавить какие-либо другие комментарии о вашем самочувствии сегодня? (Например, о настроении, физической активности, стрессе). "
        "Если нет, напишите 'Нет'.",
        reply_markup=get_cancel_keyboard()
    )
    return Q5_COMMENTS

async def q5_comments_and_save(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Завершает опрос, сохраняет данные и возвращается в главное меню."""
    comments = update.message.text
    context.user_data["survey_data"]["comments"] = comments
    user_id = update.effective_user.id
    results = context.user_data["survey_data"]
    
    # Сохраняем результаты опроса
    asyncio.create_task(save_survey_results(user_id, results))
    
    await update.message.reply_text(
        "✅ **Опрос завершен!**\n\nСпасибо за уделенное время. Ваши данные сохранены и будут использованы вашим врачом для анализа вашего состояния.\n"
        "Вы можете начать новый опрос завтра или выбрать другие опции в меню.",
        reply_markup=get_main_menu_keyboard(),
        parse_mode="Markdown"
    )
    
    # Очистка данных
    context.user_data.pop("survey_data", None)
    return ConversationHandler.END

# --- Обработчики отмены ---

async def cancel(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Обрабатывает команду /cancel и завершает текущий диалог."""
    await update.message.reply_text(
        "Действие отменено. Вы вернулись в главное меню.",
        reply_markup=get_main_menu_keyboard()
    )
    return ConversationHandler.END

async def cancel_button_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Обрабатывает нажатие кнопки '❌ Отмена'."""
    if update.message.text == CANCEL_BTN:
        await update.message.reply_text(
            "Действие отменено. Вы вернулись в главное меню.",
            reply_markup=get_main_menu_keyboard()
        )
        return ConversationHandler.END
    return ConversationHandler.END # Если не "Отмена", то это fallbacks, который должен завершить диалог.

# --- Главная функция ---

def main() -> None:
    """Запускает бота в режиме Webhook."""
    
    # 0. Проверка наличия токенов
    if not TELEGRAM_TOKEN or not RENDER_EXTERNAL_HOSTNAME:
        logger.error("❌ КРИТИЧЕСКАЯ ОШИБКА: TELEGRAM_TOKEN или RENDER_EXTERNAL_HOSTNAME не установлены.")
        logger.error("Пожалуйста, установите переменные среды на Render и перезапустите сервис.")
        return # Критический выход

    # 1. Инициализация Firebase/Firestore
    init_firebase()
    
    logger.info("Инициализация приложения Telegram Bot...")
    
    # 2. Создание Application
    # URL для Webhook будет полным URL, который мы сообщаем Telegram
    application = Application.builder().token(TELEGRAM_TOKEN).build()

    # 3. Регистрация диалогов
    
    # Диалог обратной связи
    feedback_conv_handler = ConversationHandler(
        entry_points=[MessageHandler(filters.Regex(f"^{FEEDBACK_BTN}$"), feedback_start)],
        states={
            FEEDBACK: [MessageHandler(filters.TEXT & ~filters.COMMAND & ~filters.Regex(f"^{CANCEL_BTN}$"), feedback_process)],
        },
        fallbacks=[CommandHandler("cancel", cancel), MessageHandler(filters.Regex(f"^{CANCEL_BTN}$"), cancel)],
    )

    # Диалог опроса
    survey_conv_handler = ConversationHandler(
        entry_points=[MessageHandler(filters.Regex(f"^{SURVEY_BTN}$"), survey_start)],
        states={
            Q1_PAIN: [MessageHandler(filters.TEXT & ~filters.COMMAND & ~filters.Regex(f"^{CANCEL_BTN}$"), q1_pain)],
            Q2_SLEEP: [MessageHandler(filters.TEXT & ~filters.COMMAND & ~filters.Regex(f"^{CANCEL_BTN}$"), q2_sleep)],
            Q3_MEDICATION: [MessageHandler(filters.TEXT & ~filters.COMMAND & ~filters.Regex(f"^{CANCEL_BTN}$"), q3_medication)],
            Q4_SIDE_EFFECTS: [MessageHandler(filters.TEXT & ~filters.COMMAND & ~filters.Regex(f"^{CANCEL_BTN}$"), q4_side_effects)],
            Q5_COMMENTS: [MessageHandler(filters.TEXT & ~filters.COMMAND & ~filters.Regex(f"^{CANCEL_BTN}$"), q5_comments_and_save)],
        },
        fallbacks=[CommandHandler("cancel", cancel), MessageHandler(filters.Regex(f"^{CANCEL_BTN}$"), cancel)],
    )

    # 4. Регистрация обработчиков
    application.add_handler(CommandHandler("start", start))

    # Добавляем диалоги
    application.add_handler(survey_conv_handler)
    application.add_handler(feedback_conv_handler)

    # Добавляем обработчики для кнопок-команд
    application.add_handler(MessageHandler(filters.Regex(f"^{ILLNESS_BTN}$"), show_illness_info))
    application.add_handler(MessageHandler(filters.Regex(f"^{INFO_BTN}$"), show_info))
    application.add_handler(MessageHandler(filters.Regex(f"^{EMERGENCY_BTN}$"), show_emergency))

    # Обработчик для любого другого текста (на случай, если пользователь просто пишет)
    async def other_text(update: Update, context: ContextTypes.DEFAULT_TYPE):
        await update.message.reply_text(
            "Я не понял ваш запрос. Пожалуйста, используйте кнопки меню.",
            reply_markup=get_main_menu_keyboard()
        )
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND & ~filters.Regex(f"^{SURVEY_BTN}$") & ~filters.Regex(f"^{FEEDBACK_BTN}$") & ~filters.Regex(f"^{ILLNESS_BTN}$") & ~filters.Regex(f"^{INFO_BTN}$") & ~filters.Regex(f"^{EMERGENCY_BTN}$"), other_text))


    logger.info("Application handlers set up successfully.")
    
    # 5. Запуск бота в режиме Webhook
    logger.info(f"Запуск Webhook на порту {PORT} с URL: https://{WEBHOOK_URL}")
    application.run_webhook(
        listen="0.0.0.0",
        port=PORT,
        url_path=WEBHOOK_PATH,
        webhook_url=f"https://{WEBHOOK_URL}", # Полный URL, который мы сообщаем Telegram
    )

if __name__ == "__main__":
    main()
